### ISSUE TITLE
Rakenduse koodirepositooriumi üles seadmine

### ISSUE THREAD

**Issue by artannuk** [jaagupku/spicy-memes#3]

**Comment by jaagupku** [comment]
- [x] Üks rühmaliige loob koodihaldussüsteemi uue projekti ja lisab kõik meeskonnaliikmed sinna kasutajaks
- [x] Kõik rühmaliikmed installeerivad omale sobiva Git kliendi (nt Eclipse plug-inina, sourcetree või mõne rakenduse).
- [x] Kõik rühmaliikmed lisavad repositooriumisse vähemalt ühe faili ning muudavad vähemalt ühte teise rühmaliikme poolt lisatud faili.
